Add : 네비바 초기세팅
wecode-bootcamp-korea/33-1st-Namba1-frontend pull request #1
Opened 2022-05-23 13:14 UTC by cham-min

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-05-24 06:10 UTC, younuk23 requested changes
수고하셨습니다 현민님 리뷰 확인 및 반영해주세요!

2022-05-24 06:10 UTC, younuk23 commented on package.json
> +    "git": "^0.1.5",
잘못 추가하신 것 같네요 uninstall 해주세요!

2022-05-24 06:10 UTC, younuk23 commented on src/components/Nav/Nav.js
> +      <ul className="pageMenu">
navigation 관련된 태그들을 감싸는 것이니까 nav tag도 좋겠네요

2022-05-24 06:10 UTC, younuk23 commented on src/components/Nav/Nav.js
> +        </li>
반복되는 UI는 상수데이터 + Array.map 활용해보세요!

2022-05-24 07:38 UTC, cham-min commented on package.json
> +    "git": "^0.1.5",
`npm uninstall branch`, `npm uninstall git`으로 삭제 완료했습니다.

2022-05-24 07:39 UTC, cham-min commented on src/components/Nav/Nav.js
> +      <ul className="pageMenu">
반영했습니다!

2022-05-24 07:39 UTC, cham-min commented on src/components/Nav/Nav.js
> +        </li>
반영했습니다!

2022-05-24 08:39 UTC, younuk23 requested changes
반영하신 것 코멘트 달아주시는 것 👍
리뷰 확인 및 반영해주세요~!

2022-05-24 08:39 UTC, younuk23 commented on src/components/Nav/Nav.js
> +        {PAGENAV_LIST.map(menu => {
```suggestion
        {PAGENAV_LIST.map(({id, url, page}) => {
```
매개변수자리에서 구조분해 해줘도 좋겠네요!

2022-05-24 08:39 UTC, younuk23 commented on src/components/Nav/Nav.js
> +          {MYNAV_LIST.map(myMenu => {
```suggestion
          {MY_NAV_LIST.map(myMenu => {
```
가 좀 더 적절할 것 같네요!

2022-05-24 08:39 UTC, younuk23 commented on src/components/Nav/Nav.js
> +    page: <FontAwesomeIcon icon={faCartShopping} className="cart" />,
👍

2022-05-24 08:39 UTC, younuk23 commented on src/components/Nav/Nav.js
> +import { Link } from 'react-router-dom';
4주차 리팩토링 체크리스트 확인해서 import 순서 맞춰주세요!

2022-05-24 08:39 UTC, younuk23 commented
커밋 메세지도 작업내용이 잘 드러나게 조금 더 상세하게 작성해주세요~!

2022-05-26 06:53 UTC, younuk23 commented
현민님 수정반영 하고 계신가요?? 다른 작업보다 리뷰 반영이 먼저 되어야지 master에 브랜치들이 계속 통합될 수 있습니다.

2022-05-27 02:39 UTC, younuk23 approved these changes
LGTM 👍

2022-05-27 02:39 UTC, merged