[33기 박주영] Modify , Add : 리뷰 검색 기능 구현
wecode-bootcamp-korea/33-1st-Namba1-frontend pull request #4
Opened 2022-05-24 07:17 UTC by parkjooyoung0608

## :: 최근 작업 주제
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표
- review page 
  - layout 구축
  - 리뷰쓰기 폼 기능 구현
  

<br />

## :: 구현 사항 설명
**1. review page의 JSX / SCSS 구조 잡기**
section 별로 구분
- bestReview
- searchBox
- reviewList
  - revieWrite

**2. 리뷰 반영 후** 
- 주석 컨벤션 수정 (Todo 👉🏻 TODO)
- 개인적인 내용의 주석 삭제
- 이미지 절대 경로 수정 & alt attribute 수정
- scss (tag selector 👉🏻 className 부여 후 스타일 수정)
- 컴포넌트 분리 
  - BestReview
  - ReviewBox
  - ReviewAdd
  - ReviewList
  - ReviewListItem
  - SearchBox
- array.map 메소드 사용
- 목 데이터, 상수 데이터 활용

**3. 리뷰 쓰기 기능** 
- 리뷰쓰기 클릭 후 폼 열기 
- 닫기 버튼 클릭 후 폼닫기
- ESC 키 감지 후 폼 닫기
- 폼 바깥 영역 클릭하면 폼 닫기

**4. 리뷰 검색 기능 구현**
- 돋보기 버튼 클릭 시 사용자가 검색창에 입력한 글씨가 포함된 리뷰가 나타나도록 구현

<br />

## :: 성장 포인트
- react font awesome 사용법에 대해 익혔습니다.
- `<textarea/>` 는  `resize: none;`으로 크기 조절 창을 없앤 후 크기 고정이 가능하다는 걸 알았습니다. 
- 하드 코딩 후 컴포넌트 화 시키는게 생각보다 번거롭고, 같은 작업을 굳이 두번하는 느낌을 받았습니다. 컴포넌트 화의 중요성을 깨달은 작업이었습니다. 
- 실제 데이터가 백엔드 API로 온다면 목데이터 사용, 정적인 내용인데 반복된다면 상수 데이터 활용하면 된다는 사실을 알게되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-05-24 07:39 UTC, younuk23 requested changes
수고하셨습니다 주영님 리뷰 확인 및 반영해주세요!

2022-05-24 07:39 UTC, younuk23 commented on src/pages/Review/Review.js
> +        {/* Todo : 수동 슬라이드 기능 구현 */}
TODO(대문자)가 컨벤션입니다!
```suggestion
        {/* TODO : 수동 슬라이드 기능 구현 */}
```

2022-05-24 07:39 UTC, yeonuk-hwang commented on src/pages/Review/Review.js
> +              <img src="images/review/food1.jpg" alt="d" />
절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!

예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.

2022-05-24 07:39 UTC, younuk23 commented on src/pages/Review/Review.js
> +              <img src="images/review/food1.jpg" alt="d" />
alt attribute도 의미있게 채워주세요~!

2022-05-24 07:39 UTC, younuk23 commented on src/pages/Review/Review.js
> +          </div>
비슷한 UI가 반복되는 것 같네요 Array.map 메소드를 이용해서 구현하면 훨씬 깔끔하고 유지보수하기 용이합니다

2022-05-24 07:39 UTC, yeonuk-hwang commented on src/pages/Review/Review.js
> +            {/* 이거 어떻게...? */}
고뇌의 흔적은 알겠으나.... PR에서 들키게하진 말아주세요 :)

2022-05-24 07:39 UTC, younuk23 commented on src/pages/Review/Review.js
> +}
Review 컴포넌트 안에 전체적으로 반복되는 UI가 많이 보이네요!!

추후 나중에 API를 통해서 받아올 데이터라면 목데이터, 고정적인 데이터라면 상수데이터 등과 함께 Array.map 메서드를 활용하시는 방향이 더 좋습니다!

그리고, 처음에 바로 하드코딩으로 전체로 만들어놓고 나중에 깔끔하게 변경하는 것보다 처음부터 컴포넌트로 만들면서 하나하나 합쳐가는 식으로 하시는게 더 좋습니다!

2022-05-24 07:39 UTC, yeonuk-hwang commented on src/pages/Review/Review.scss
> +$gray: #606060;
위의 mixin, $gray 등이 이 scss 파일 안에서만 쓰일 요소들이면 여기 있어도 되지만 만약 다른데서도 공통적으로 사용될 확률이 있다면 variables에 추가해서 사용해주세요!

2022-05-24 07:39 UTC, younuk23 commented on src/pages/Review/Review.scss
> +    form {
- div 태그 처럼 빈번히 사용되는 태그로 스타일을 주는 건 depth에 무관하게 적용되어 의도치 않은 스타일링이 될 수 있습니다. 클래스 셀렉터(ex. `.foo`)를 사용해주세요.
- tag selector는 해당 요소 뿐만 아니라 동일한 태그로 선언된 다른 요소들에게도 영향을 미칠 여지가 너무 많기 때문에 추후 유지보수에 악영향을 미칠 수 있습니다.
- 스타일링을 줄 때는 요소마다 className을 부여하셔서 스타일링을 주시는게 좋습니다.

2022-05-24 07:41 UTC, younuk23 commented
전체적인 코드가 너무 지저분 한 것 같습니다.. 좀 더 깔끔하게 작성할 수 있는 방법이 있을까요...?
=> 저 포함 전세계 모든 개발자들이 지금도 실시간으로 하고 있는 고민이네요..... :( 결국 이게 개발 잘하는법과 동일한 의미라서 어떻게하면 좀 더 좋은 코드를 작성할 수 있을까 계속 고민하고 적용해보면서 느는방법밖에 없습니다! 혹시 비법 아시게 되면 저한테도 공유해주세요 ㅋㅋㅋ

2022-05-24 07:49 UTC, parkjooyoung0608 commented on src/pages/Review/Review.scss
> +$gray: #606060;
공통 사용은 아니어서 그대로 두겠습니다!

2022-05-25 01:27 UTC, younuk23 commented on src/components/Review/ReviewAdd.js
> +    fetch('data/menu.json')
절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!

예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.

2022-05-25 01:27 UTC, younuk23 commented on src/components/Review/ReviewAdd.js
> +    fetch('data/menu.json')
```suggestion
    fetch('/data/menu.json')
```

2022-05-25 01:27 UTC, younuk23 commented on src/components/Review/ReviewAdd.js
> +          ))}
```suggestion
          {menu.map(({id, menuName}) => (
            <option key={id}>{menuName}</option>
          ))}
```
매개변수자리에서 구조분해해주면 좀 더 깔끔하겠네요

2022-05-25 01:27 UTC, younuk23 commented on src/components/Review/ReviewList.js
> +  // ];
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-05-25 01:27 UTC, younuk23 commented on src/components/Review/ReviewList.js
> +  ]);
처음부터 리뷰가 하나 들어가 있는게 실제 상황과 비교했을 때 적절하진 않은 것 같네요! 처음에는 리뷰가 비어있다가 나중에 데이터 통신을 통해서 실제 리뷰가 state에 채워지는 동작이 알맞아보입니다! 따라서, 초기값은 빈배열로 주는게 좋겠네요!

```suggestion
  const [reviewItem, setReviewItem] = useState([]);
```

2022-05-25 01:27 UTC, younuk23 commented on src/components/Review/ReviewList.js
> +  }, []);
여기도 절대경로! 다른 부분들도 확인해주세요~!

2022-05-25 01:27 UTC, younuk23 commented on src/components/Review/ReviewList.js
> +  ]);
변수명에 Item등의 단어는 굳이 안들어가도 될 것 같네요 reviews 정도로만 해도 적절해보입니다!

2022-05-25 01:27 UTC, younuk23 commented on src/components/Review/ReviewList.js
> +      {reviewItem.map(item => (
매개변수자리에서 구조분해할당 해주면 깔끔하겠네요!

2022-05-25 01:27 UTC, younuk23 commented on src/components/Review/ReviewListItem.js
> +export default ReviewListItem;
하나의 파일엔 하나의 컴포넌트만 있도록 해주세요!

2022-05-25 01:27 UTC, younuk23 commented on src/components/Review/ReviewListItem.js
> +      <span className="tipHead" style={{ fontWeight: 700 }}>
inline style nope!

2022-05-25 01:27 UTC, yeonuk-hwang commented on src/pages/Review/Review.scss
> +$gray: #606060;
👍

2022-05-25 01:27 UTC, younuk23 commented on src/pages/Review/Review.scss
> +}
Review 컴포넌트의 자식 컴포넌트들 스타일도 여기에 다 포함되어 있는 것 같네요!

2022-05-25 01:30 UTC, younuk23 requested changes
수고하셨습니다 리뷰 확인 및 반영해주세요!

2022-05-25 01:30 UTC, younuk23 commented on src/pages/Review/Review.scss
> +}
컴포넌트는 독립적이고 재사용될 수 있어야 합니다
어떤 컴포넌트에 대한 스타일시트에서 컴포넌트 외의 요소에 대해서 접근해서 스타일을 부여한다면 그 컴포넌트는 독립적이라고 볼 수 없습니다.
컴포넌트의 스타일 시트는 해당 컴포넌트에 대한 스타일만 진행해주세요!

2022-05-25 01:30 UTC, younuk23 commented on src/components/Review/ReviewList.js
> +  ]);
다른 부분도 유사한 사항 확인해주세요!

2022-05-25 01:30 UTC, younuk23 commented on src/components/Review/ReviewAdd.js
> +            </span>
이렇게 유사한 형태가 반복되는 경우 Array.map을 이용해서 처리하면 좋겠네요!
Slider1, 2, 3 부분도 마찬가지입니다!!

실제 데이터가 백엔드에서 온다면 목데이터로 API를 모방하고, 나중에 실 API로 교체하면 되고(ex: 리뷰 데이터)
이렇게, 정적인 내용인데 반복된다면 상수데이터를 활용하면 되겠네요!

2022-05-25 03:41 UTC, parkjooyoung0608 commented on src/components/Review/ReviewAdd.js
> +    fetch('data/menu.json')
같은 실수를 했네요..😭😭 습관을 빨리 고쳐야겠어요ㅠㅠ...

2022-05-26 01:52 UTC, younuk23 requested changes
- 처음 올라온 PR 상태보다 훨씬 깔끔해졌네요 👍 
- 다만, 실수한 부분들이 몇개 보이는데 한번씩만 더 확인하면 충분히 고칠 수 있는 부분들입니다! 항상 작업물에 책임감 가지고 꼼꼼히 확인해주세요!

2022-05-26 01:52 UTC, younuk23 commented on src/components/Review/ReviewAdd.js
> +  const DETAILS_DESC = [
- 이 값 같은 경우에는 매 rendering 마다 새롭게 선언되고 할당될 필요는 없어보입니다.
- 이런 상수데이터를  함수형 컴포넌트 본문 안에서 선언하게 되면 rendering이 일어날때 마다 매번 데이터를 만들고 변수에 값을 할당하는 연산이 일어나게 됩니다.
- 따라서 성능에 악영향을 미칠 수 있습니다.
- 컴포넌트가 사용하는 데이터라고 컴포넌트 안에만 위치할 필요는 없습니다
- 통상 이런 상수데이터같은 경우에는 여러 컴포넌트에서 동시에 사용하는 데이터라면 별도 파일로 분리하거나,이 컴포넌트 안에서만 사용하는 데이터라면 컴포넌트 하단에 작성해줍니다
- 상수데이터의 네이밍은 상수데이터임을 표시하기 위해서 UPPERCASER + snake_case 로 작성해주는게 컨벤션입니다

2022-05-26 01:52 UTC, younuk23 commented on src/components/Review/ReviewAdd.js
> +  }, [setReviewAdd]);
👍

2022-05-26 01:52 UTC, younuk23 commented on src/components/Review/ReviewAdd.js
> +      {ReviewAdd ? (
실수하신 것 같네요!

PR 올리신 후에는 반드시 github에서 File Changed 탭 확인해서 내가 작성한 코드에 실수는 없는지, 내가 의도하지 않은 작업물들이 올라가지 않았는지 확인하는 습관을 들여주세요! PR을 요청할 때의 마음가짐은 실제 내가 등록한 코드가 바로 배포되어서 유저들이 바로 사용하게 된다고 생각하고 해주세요.(당연히 지금은 학습과정이니까 작업이 완료되지 않아도 피드백을 목적으로 추가기능구현중 라벨을 붙이고 PR을 요청할수도 있지만 리뷰 요청하기 전에는 스스로 한번 꼭 점검해주세요!!)

2022-05-26 01:52 UTC, younuk23 commented on src/components/Review/ReviewAdd.js
> +const ReviewAdd = ({ reviewAdd, setReviewAdd }) => {
boolean값이라면 isReviewAdd 등의 이름이 좀 더 boolean 인 것을 인지할 수 있겠네요!

2022-05-26 01:52 UTC, younuk23 commented on src/components/Review/ReviewAdd.js
> +                  <span key="id" className="detail">
속을뻔 했네요...
```suggestion
                  <span key={id} className="detail">
```

2022-05-26 01:52 UTC, younuk23 commented on src/components/Review/ReviewAdd.js
> +                  <span key="id" className="detail">
warning 출력 됬을 것 같은데 실행하면서 항상 의도한 대로 동작하는지 콘솔창에 경고는 안뜨는지 확인해주세요!

2022-05-26 01:52 UTC, younuk23 commented on src/components/Review/ReviewBox.js
> +  const onClick = () => {
함수의 이름은 이 함수가 어떤 동작을 하는지 알 수 있게 해주세요, onClick이란 함수이름으로는 어떤 동작을 하는지 파악할 수가 없습니다! 항상 이름짓기 잘 고민해주세요!

2022-05-27 02:45 UTC, younuk23 requested changes
코드가 깔끔하네요!! 👍 👍 👍 
리뷰 드린 내용중 isReviewAdd 잘못 넣은 부분 해결해주시고, 컨플릭트 해결해주세요!!!

2022-05-27 02:45 UTC, younuk23 commented on src/components/Review/ReviewAdd.js
> +  // 세터 함수를 넣는게 맞나요...?
네 setState 함수를 말하는 거라면 맞습니다!, setState 함수는 useState 내부에서 매번 렌더링이 되도 안변하도록 처리를 해주기 때문에 useEffect 의존성 배열에 넣어줘도 빈배열 넣은것과 동일하게 마운트시에만 이펙트가 발동합니다!

의존성배열에 대한 자세한 내용을 이해하기 위해서는 클로저, primitive type, reference type등 다양한 개념의 이해가 필요합니다.
useEffect에 관련되서 아래의 잘 정리된 아티클 하나 공유드립니다!
당장 이해안되더라도 나중에 찬찬히 읽어보고 찾아보시면 좋을것 같습니다!
[useEffect 완벽 가이드](https://www.rinae.dev/posts/a-complete-guide-to-useeffect-ko)

위 내용은 지금은 당연히 이해하시기 어려우니까 저장해놨다가 찬찬히 조금씩 이해해보세요!

2022-05-27 02:45 UTC, younuk23 commented on src/components/Review/ReviewAdd.js
> +  }, [isReviewAdd]);
여기는 이펙트 내에서 isReviewAdd 함수를 사용하고 있지 않아서, isReviewAdd 함수가 의존성배열에 들어갈 필요가 없겠네요!

2022-05-27 02:59 UTC, younuk23 commented
- lock 파일은 패키지 변화 히스토리 트리가 담겨있어서 프로젝트 버전이랑 함께 관리 되어야 합니다. lock 파일이 없다면 현재 프로젝트에서 사용하고 있는 버전이 아닌 최신 버전이 계속 설치됩니다.
- lock.json 파일 컨플릭트 해결 방법
    1. package.json 파일의 컨플릭트 해결
    2. `npm install --package-lock-only`
- 참고 링크 : [https://dltlabs.medium.com/package-json-vs-package-lock-json-c8d5deba12cb](https://dltlabs.medium.com/package-json-vs-package-lock-json-c8d5deba12cb)
package-lock의 컨플릭트는 위 코멘트 참고해주세요!

2022-05-27 09:02 UTC, younuk23 approved these changes
LGTM 👍

2022-05-27 09:02 UTC, merged

2022-05-27 09:03 UTC, younuk23 commented
주영님! 제가 추가기능 구현중 라벨 확인을 못해서 바로 머지했는데 혹시 이 브랜치에서 추가로 작업하신 내용 있으면 다시 push 하고 PR 등록해주시면 됩니다!! 없으시면 다른 브랜치에서 이어서 작업해주시면 됩니다!