[33기 김혜수] ADD : Signup Layout
wecode-bootcamp-korea/33-1st-Namba1-frontend pull request #5
Opened 2022-05-24 09:02 UTC by keemhyesu

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-05-24 09:04 UTC, ghost commented on src/pages/Signup/Signup.js
> +import React, { useCallback } from 'react';
__[ESLint]__ 'useCallback' is defined but never used. ([view](https://sider.review/gh/repos/495294259/pulls/5#issue-6955638))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-unused-vars` | `warn` | Yes |

References:
- <https://eslint.org/docs/rules/no-unused-vars>

You can [close this issue](https://sider.review/gh/repos/495294259/pulls/5#issue-6955638) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-05-25 07:15 UTC, yeonuk-hwang requested changes
고생하셨습니다 혜수님! 리뷰 확인 및 반영해주세요!

2022-05-25 07:15 UTC, yeonuk-hwang commented on src/index.js
> +// import Signin from './pages/Signin/Signin';
불필요한 주석 및 코드인 것 같네요!!

PR 올리신 후에는 반드시 github에서 File Changed 탭 확인해서 내가 작성한 코드에 실수는 없는지, 내가 의도하지 않은 작업물들이 올라가지 않았는지 확인하는 습관을 들여주세요!

2022-05-25 07:15 UTC, yeonuk-hwang commented on src/pages/Signin/Signin.js
> +  // const disable = inputId.includes('@') && inputPw.length >= 1 ? true : false;
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-05-25 07:15 UTC, yeonuk-hwang commented on src/pages/Signin/Signin.js
> +    <div>
전체적으로 최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅 하는 부분이 적용안되어있습니다. 이렇게 되면 동일한 className을 가진 다른 컴포넌트의 요소들에게도 영향을 미칠 수 있습니다.
**최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅** 적용해주세요

예시)

```jsx
const ProductDetail = () => {

	return(
		<section className="productDetail">
			~~~~
		</section>
	)
}
```

2022-05-25 07:15 UTC, yeonuk-hwang commented on src/pages/Signin/Signin.scss
> +.loginForm {
네스팅 적용해주세요!!

2022-05-25 07:15 UTC, yeonuk-hwang commented on src/pages/Signin/Signin.scss
> +}
네스팅 잘 되어있다고 하면  tag.className 형태로 안쓰고 그냥 .className으로만 작성해도 될 것 같네요!

2022-05-25 07:15 UTC, younuk23 commented on src/pages/Signin/Signin.js
> +  // const disable = inputId.includes('@') && inputPw.length >= 1 ? true : false;
사용할려는 기능이면, 코드 작성해주시면 되고 아니라면 삭제헤주시면 될 것 같네요!

이전 코드 참고하는 것은 좋지만 그대로 카피 페이스트 하는 것 보다 필요한 부분들을 잘 조합해서 수정해서 사용하시는게 좋습니다!!

2022-05-25 07:15 UTC, yeonuk-hwang commented on src/pages/Signup/Signup.scss
> +  }
```suggestion
  .terms {
    margin-bottom: 0.625rem;
  }
```
동일한 스타일을 부여할 것이라면, 각자 다른 className을 줄 필요 없이 하나의 className으로 처리하면 될 것 같네요!!

className의 궁극적인 목적은 스타일을 주기 위함입니다, 항목들이 다르다고 똑같은 스타일을 부여할 것인데 다른 className을 부여할 필요는 없습니다!

2022-05-25 07:15 UTC, yeonuk-hwang commented on src/pages/Signup/Signup.scss
> +  margin-top: 1.25rem;
- CSS 속성은 레이아웃에 영향을 많이 주는 순서대로, 인접 속성끼리 묶어서 
작성해주는게 좋습니다. 
- 일전에 안내해드린 [css 속성순서 컨벤션](https://study.wecode.co.kr/session/content/193) 확인하시고 지켜서 작성해주세요

2022-05-25 07:15 UTC, younuk23 commented on src/pages/Signup/Signup.scss
> +  }
다른 부분도 마찬가지로 적용되는 코멘트니까 전반적으로 확인 및 수정해주세요~!

2022-05-25 07:15 UTC, younuk23 commented on src/pages/Signup/Signup.js
> +          </div>
반복되는 UI로 보이네요, 반복되는 UI는 하드코딩 하는 것 보다 Array.map 메서드를 활용하면 코드가 깔끔해지고, 유지보수에 용이해집니다.

2022-05-27 02:45 UTC, younuk23 commented
혜수님 리뷰 반영하고 계시죠?? 혹시 다른 작업 하고 계신겨면 리뷰 반영 우선적으로 진행해주시고, 반영 하시고 push 및 라벨 변경해주세요!

2022-05-27 09:04 UTC, younuk23 commented
혜수님 리뷰요청 전 사이더 코멘트 해결해주세요!!, 브랜치 머지되면서 컨플릭 발생했는데 컨플릭도 해결해주세요!!
package-lock.json 컨플릭트는 아래 코멘트 확인해보시면 됩니다!

- lock 파일은 패키지 변화 히스토리 트리가 담겨있어서 프로젝트 버전이랑 함께 관리 되어야 합니다. lock 파일이 없다면 현재 프로젝트에서 사용하고 있는 버전이 아닌 최신 버전이 계속 설치됩니다.
- lock.json 파일 컨플릭트 해결 방법
    1. package.json 파일의 컨플릭트 해결
    2. `npm install --package-lock-only`
- 참고 링크 : [https://dltlabs.medium.com/package-json-vs-package-lock-json-c8d5deba12cb](https://dltlabs.medium.com/package-json-vs-package-lock-json-c8d5deba12cb)

2022-05-29 09:13 UTC, keemhyesu commented on src/components/SignUpForm.js
> +  const [inputValue, setInputValue] = useState({
@younuk23 연욱님 ㅠㅠㅠㅜㅠ 이부분 해결을 못하고있습니다..help me..도와주세요...

2022-05-29 09:13 UTC, keemhyesu commented on src/components/SignUpForm.js
> +  const [inputValue, setInputValue] = useState({
이 부분도...마찬가지입니다..ㅜㅜㅜㅜ

2022-05-30 02:41 UTC, younuk23 commented
혜수님 사이더 해결 해주시고, 라벨 변경해주세요!

2022-05-30 08:22 UTC, ghost commented on src/components/SignUpForm.js
> +  const { name, value, id, title, type } = input;
__[ESLint]__ 'value' is assigned a value but never used. ([view](https://sider.review/gh/repos/495294259/pulls/5#issue-6966143))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-unused-vars` | `warn` | Yes |

References:
- <https://eslint.org/docs/rules/no-unused-vars>

You can [close this issue](https://sider.review/gh/repos/495294259/pulls/5#issue-6966143) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-05-30 08:24 UTC, keemhyesu reviewed
-

2022-05-30 08:28 UTC, keemhyesu commented
> asdasdasdasd

2022-05-31 09:38 UTC, younuk23 commented
- conflict 해결해주세요!, lock 파일 컨플릭트 해결은 아래 코멘트 참고해주세요
- lock 파일은 패키지 변화 히스토리 트리가 담겨있어서 프로젝트 버전이랑 함께 관리 되어야 합니다. lock 파일이 없다면 현재 프로젝트에서 사용하고 있는 버전이 아닌 최신 버전이 계속 설치됩니다.
- lock.json 파일 컨플릭트 해결 방법
    1. package.json 파일의 컨플릭트 해결
    2. `npm install --package-lock-only`
- 참고 링크 : [https://dltlabs.medium.com/package-json-vs-package-lock-json-c8d5deba12cb](https://dltlabs.medium.com/package-json-vs-package-lock-json-c8d5deba12cb)

2022-06-02 01:31 UTC, yeonuk-hwang reviewed
LGTM, 리팩토링 하실 때 라이브 코드 리뷰 때 말씀드린 allCheck state 없애는 것도 꼭 시도해보세요!

2022-06-02 01:31 UTC, merged