[33기 최현민] Add : Feature/main layout
wecode-bootcamp-korea/33-1st-Namba1-frontend pull request #7
Opened 2022-05-25 08:57 UTC by cham-min

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-05-27 04:42 UTC, younuk23 requested changes
수고하셨습니다! 리뷰 확인 및 반영해주세요!!
커밋 자주 남기시는 것 좋네요 👍 👍 👍

2022-05-27 04:42 UTC, younuk23 commented on src/components/Main/MainCarousel.js
> +    if (currentSlide >= TOTAL_SLIDES) {
MAIN_SLIDE.length - 1로 TOTAL_SLIDES 값 사용하는게 좋겠네요!!

3이라는 고정값을 TOTAL_SLIDE에 넣어두면 추후 슬라이드 갯수가 변경됬을 때 관리해야하는 게 하나 더 늘어납니다!

2022-05-27 04:42 UTC, younuk23 commented on src/components/Main/MainCarousel.js
> +        })}
```suggestion
        {MAIN_SLIDE.map(({ id, src, alt }) => <img key={id} className="mainSlide" src={src} alt={alt} />)}
```
arrow function에서 바로 return 할 경우에는 중괄호 및 return 키워드 생략 가능합니다!

2022-05-27 04:42 UTC, younuk23 commented on src/components/Main/Menu.js
> +export default Menu;
Menu와 MDMenu 하나의 컴포넌트로 재사용할 수 있는 방법이 있을 것 같네요!

2022-05-27 04:42 UTC, younuk23 commented on src/components/Main/MenuInfo.js
> +    <div className="itemInfo">
전체적으로 최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅 하는 부분이 적용안되어있습니다. 이렇게 되면 동일한 className을 가진 다른 컴포넌트의 요소들에게도 영향을 미칠 수 있습니다.
**최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅** 적용해주세요

예시)

```jsx
const ProductDetail = () => {

	return(
		<section className="productDetail">
			~~~~
		</section>
	)
}
```

최상위 className 항상 신경써 주세요!

2022-05-27 04:42 UTC, younuk23 commented on src/components/Main/NewProduct.js
> +    fetch('http://localhost:3000/data/newProduct.json', {
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2022-05-27 04:42 UTC, younuk23 commented on src/components/Main/NewProduct.js
> +      {newProduct.map(newProduct => {
매개변수 자리에서 구조분해할당 하는게 좋겠네요!

2022-05-27 04:42 UTC, younuk23 commented on src/components/Main/NewProduct.js
> +                  {' '}
이런 실수들 다 확인해주세요 꼼꼼히!

2022-05-27 04:42 UTC, younuk23 commented on src/components/Main/Recommend.js
> +// import { faAngleDown } from '@fortawesome/free-solid-svg-icons';
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-05-27 04:42 UTC, younuk23 commented on src/components/Main/Recommend.js
> +  const TOTAL_SLIDES = 3;
이전에 남겨드린 코멘트와 동일합니다!

2022-05-27 04:42 UTC, younuk23 commented on src/components/Main/MenuInfo.js
> +    <div className="itemInfo">
이 부분말고도 코드 전체적으로 동일한 사항 확인해주세요!

2022-05-27 04:51 UTC, cham-min commented on src/components/Main/MainCarousel.js
> +    if (currentSlide >= TOTAL_SLIDES) {
신경을 쓰고 있었는데 고칠 생각을 못했네요ㅜㅜ 해결책 감사합니다!!

2022-05-27 06:45 UTC, cham-min commented on src/components/Main/MenuInfo.js
> +    <div className="itemInfo">
기본적인 부분을 놓치고 있었네요. 클래스 이름을 짓기 전에 종이에 HTML 박스모델 구성을 그리면서 클래스이름을 신경써서 적도록 해보겠습니다.

2022-05-27 06:47 UTC, cham-min commented on src/components/Main/NewProduct.js
> +    fetch('http://localhost:3000/data/newProduct.json', {
생략하면 간결해 보일 뿐만이 아니라 에러를 방지할 수 있다는 점은 처음 알았네요 감사합니다 : ]

2022-05-27 06:52 UTC, cham-min commented on src/components/Main/NewProduct.js
> +      {newProduct.map(newProduct => {
똑같은 실수 두 번 반복하네요. 적어놓고 매 번 확인하겠습니다!

2022-05-30 05:02 UTC, cham-min commented on src/components/Main/Menu.js
> +export default Menu;
계속 고민중인 문제입니다.. 더 생각해보고 도움 요청하겠습니다.

2022-05-31 07:35 UTC, younuk23 approved these changes

2022-05-31 07:35 UTC, merged